let fs=require('fs')
//fs.mkdirSync('folder1')
// fs.writeFileSync('folder1/file1.txt','hi i am created by----')
//  fs.appendFileSync('folder1/file1.txt','MR. Mouli')
//fs.delFileSync('../http/file1.txt')
// let data=fs.readFileSync('folder1/file1.txt','utf-8')
// console.log(data)
// fs.unlinkSync('../http/file1.txt)
// fs.createFileSync('folder1/file2.txt')